import path from 'node:path'
import {defineConfig} from 'vitest/config'

const aliasObj = {
	'@main': path.resolve('src/main'),
	'@preload': path.resolve('src/preload'),
	'@renderer': path.resolve('src/renderer/src'),
	'@shared': path.resolve('src/shared'),
	'electron-log/main.js': path.resolve('tests/__mocks__/electron-log-main.ts'),
	'electron-log/renderer.js': path.resolve('tests/__mocks__/electron-log-renderer.ts'),
	electron: path.resolve('tests/__mocks__/electron.ts')
}

// `unplugin-icons` virtual modules (`~icons/simple-icons/x`,
// `~icons/logos/facebook`, etc.) are generated by the Vite plugin at build
// time. Vitest doesn't run that plugin — without a regex alias, every test
// that transitively imports ShareDialog crashes on import resolution. Map
// every `~icons/*` to a single inert SVG stub.
const alias = [...Object.entries(aliasObj).map(([find, replacement]) => ({find, replacement})), {find: /^~icons\/.*/, replacement: path.resolve('tests/__mocks__/icons-stub.tsx')}]

export default defineConfig({
	test: {
		projects: [
			{resolve: {alias}, test: {name: 'node', globals: true, include: ['tests/**/*.test.ts'], environment: 'node', setupFiles: ['tests/setup.ts']}},
			{resolve: {alias}, test: {name: 'jsdom', globals: true, include: ['tests/**/*.test.tsx'], environment: 'jsdom', setupFiles: ['tests/setup.ts']}}
		]
	}
})
