import path from 'node:path'
import {defineConfig} from 'vitest/config'

const aliasObj = {
	'@main': path.resolve('src/main'),
	'@preload': path.resolve('src/preload'),
	'@renderer': path.resolve('src/renderer/src'),
	'@shared': path.resolve('src/shared'),
	'yt-dlp-bridge/parsers': path.resolve('packages/yt-dlp-bridge/src/parsers.ts'),
	'yt-dlp-bridge/redaction': path.resolve('packages/yt-dlp-bridge/src/redaction.ts'),
	'yt-dlp-bridge': path.resolve('packages/yt-dlp-bridge/src/index.ts'),
	'ytdlp-errors': path.resolve('packages/ytdlp-errors/src/index.ts'),
	// Workspace packages are consumed by source path, mirroring the `@arclio/*`
	// entries in tsconfig.json. Without these, any test that reaches
	// MetadataService fails to resolve the import.
	'@arclio/metadata': path.resolve('packages/metadata/src/index.ts'),
	'@arclio/media': path.resolve('packages/media/src/index.ts'),
	'electron-log/main.js': path.resolve('tests/__mocks__/electron-log-main.ts'),
	'electron-log/renderer.js': path.resolve('tests/__mocks__/electron-log-renderer.ts'),
	electron: path.resolve('tests/__mocks__/electron.ts')
}

// `unplugin-icons` virtual modules (`~icons/simple-icons/x`,
// `~icons/logos/facebook`, etc.) are generated by the Vite plugin at build
// time. Vitest doesn't run that plugin — without a regex alias, every test
// that transitively imports ShareDialog crashes on import resolution. Map
// every `~icons/*` to a single inert SVG stub.
const alias = [...Object.entries(aliasObj).map(([find, replacement]) => ({find, replacement})), {find: /^~icons\/.*/, replacement: path.resolve('tests/__mocks__/icons-stub.tsx')}]

// Vitest's 5s default is too tight for this suite: the jsdom projects render the
// full App tree and drive it through userEvent, and `bun run check` runs the
// test lane concurrently with typecheck/knip/madge/lint. Under that contention
// heavy specs blew the default timeout and the mandated quality gate failed with
// ~50 timeouts and zero assertion failures. These budgets are generous enough to
// absorb a loaded machine while still catching a genuine hang.
const TEST_TIMEOUT_MS = 20_000
const HOOK_TIMEOUT_MS = 20_000

export default defineConfig({
	test: {
		projects: [
			{resolve: {alias}, test: {name: 'node', globals: true, include: ['tests/**/*.test.ts'], environment: 'node', setupFiles: ['tests/setup.ts'], testTimeout: TEST_TIMEOUT_MS, hookTimeout: HOOK_TIMEOUT_MS}},
			{resolve: {alias}, test: {name: 'jsdom', globals: true, include: ['tests/**/*.test.tsx'], environment: 'jsdom', setupFiles: ['tests/setup.ts'], testTimeout: TEST_TIMEOUT_MS, hookTimeout: HOOK_TIMEOUT_MS}}
		]
	}
})
