import {createRequire} from 'node:module'
import {readFile} from 'node:fs/promises'
import path from 'node:path'

/**
 * Renders the first page of a PDF to a PNG buffer, in the main process.
 *
 * pdf.js is a browser library: it expects `Path2D`, `DOMMatrix` and `ImageData`
 * to exist as globals and draws into a DOM canvas. Node has none of those, so
 * the globals are filled in from `@napi-rs/canvas` (a prebuilt native canvas —
 * no node-gyp) before pdf.js is loaded. Without them pdf.js fails deep inside
 * `CanvasGraphics.fill` with `Value is none of these types Path`.
 *
 * Both modules are imported lazily so that the ~4MB pdf.js payload and the
 * native canvas binding stay out of the app's startup path — thumbnails are
 * generated by the indexer, long after boot.
 */

type CanvasModule = typeof import('@napi-rs/canvas')

let canvasModulePromise: Promise<CanvasModule> | null = null

async function loadCanvasModule(): Promise<CanvasModule> {
	canvasModulePromise ??= (async () => {
		const canvas = await import('@napi-rs/canvas')
		// `??=` so a host that already provides these (tests, future Electron
		// versions) keeps its own implementation.
		globalThis.Path2D ??= canvas.Path2D as unknown as typeof globalThis.Path2D
		globalThis.DOMMatrix ??= canvas.DOMMatrix as unknown as typeof globalThis.DOMMatrix
		globalThis.ImageData ??= canvas.ImageData as unknown as typeof globalThis.ImageData
		return canvas
	})()
	return canvasModulePromise
}

/**
 * Directory holding pdf.js' bundled metric files for the 14 standard PDF fonts.
 * Best effort: without it pdf.js only warns and still rasterises the page, so a
 * resolution failure must not fail the thumbnail.
 */
function resolveStandardFontDataUrl(): string | undefined {
	try {
		const require = createRequire(import.meta.url)
		const pdfjsRoot = path.dirname(require.resolve('pdfjs-dist/package.json'))
		return path.join(pdfjsRoot, 'standard_fonts') + path.sep
	} catch {
		return undefined
	}
}

// PDFs are rasterised from arbitrary user-imported/library files — a
// corrupted or pathologically complex page (deeply nested vector paths,
// malformed content streams pdf.js loops trying to recover from) can hang
// getDocument()/page.render() indefinitely. Without a bound, that stalls the
// main-process thumbnail pipeline with no way for the caller to give up.
const RENDER_TIMEOUT_MS = 30_000

function withTimeout<T>(promise: Promise<T>, ms: number, message: string): Promise<T> {
	return new Promise<T>((resolve, reject) => {
		const timer = setTimeout(() => reject(new Error(message)), ms)
		promise.then(
			value => {
				clearTimeout(timer)
				resolve(value)
			},
			err => {
				clearTimeout(timer)
				reject(err)
			}
		)
	})
}

export async function renderPdfFirstPage(pdfPath: string, maxWidth: number, maxHeight: number): Promise<Buffer> {
	const canvasModule = await loadCanvasModule()
	// The legacy build is the one that runs outside a browser bundler.
	const pdfjs = await import('pdfjs-dist/legacy/build/pdf.mjs')

	const data = new Uint8Array(await readFile(pdfPath))
	const task = pdfjs.getDocument({
		data,
		// Thumbnails rasterise untrusted files from the user's library. pdf.js v6
		// dropped its eval-based font path entirely, so there is no longer an
		// `isEvalSupported` switch to turn off. `disableFontFace` keeps glyphs on
		// the built-in rasteriser instead of registering document-supplied fonts.
		disableFontFace: true,
		standardFontDataUrl: resolveStandardFontDataUrl()
	})

	try {
		const document = await withTimeout(task.promise, RENDER_TIMEOUT_MS, `Timed out loading PDF after ${RENDER_TIMEOUT_MS}ms: ${pdfPath}`)
		const page = await document.getPage(1)
		const unscaled = page.getViewport({scale: 1})
		// `fit: inside` semantics — scale by the tighter axis so the page fits the
		// box whole, and never enlarge a page that is already smaller.
		const scale = Math.min(maxWidth / unscaled.width, maxHeight / unscaled.height)
		const viewport = page.getViewport({scale})
		const canvas = canvasModule.createCanvas(Math.max(1, Math.round(viewport.width)), Math.max(1, Math.round(viewport.height)))
		const context = canvas.getContext('2d')
		// PDF pages assume white paper; the canvas starts transparent and would
		// flatten to black in the JPEG the caller writes.
		context.fillStyle = '#ffffff'
		context.fillRect(0, 0, canvas.width, canvas.height)

		const renderTask = page.render({canvasContext: context as unknown as CanvasRenderingContext2D, viewport, canvas: canvas as unknown as HTMLCanvasElement})
		try {
			await withTimeout(renderTask.promise, RENDER_TIMEOUT_MS, `Timed out rendering PDF page after ${RENDER_TIMEOUT_MS}ms: ${pdfPath}`)
		} catch (err) {
			renderTask.cancel()
			throw err
		}

		return canvas.toBuffer('image/png')
	} finally {
		await task.destroy()
	}
}
