export const IPC_CHANNELS = {
	appWarmUp: 'app:warmUp',
	appCancelWarmup: 'app:cancelWarmup',
	appGetGraphicsPolicy: 'app:getGraphicsPolicy',
	appInstallYtDlpHomebrew: 'app:installYtDlpHomebrew',
	appInstallYtDlpWinget: 'app:installYtDlpWinget',
	downloadsStart: 'downloads:start',
	downloadsCancel: 'downloads:cancel',
	downloadsPause: 'downloads:pause',
	downloadsResume: 'downloads:resume',
	downloadsProbe: 'downloads:probe',
	downloadsProbeCancel: 'downloads:probeCancel',
	downloadsProbeProgress: 'downloads:probeProgress',
	chooseFolder: 'dialog:chooseFolder',
	chooseFile: 'dialog:chooseFile',
	settingsGet: 'settings:get',
	settingsUpdate: 'settings:update',
	appSetLanguage: 'app:setLanguage',
	shellOpenFolder: 'shell:openFolder',
	shellOpenExternal: 'shell:openExternal',
	logsOpenDir: 'logs:openDir',
	logsUploadFeedbackDiagnostic: 'logs:uploadFeedbackDiagnostic',
	eventsStatus: 'events:status',
	eventsProgress: 'events:progress',
	windowMinimize: 'window:minimize',
	windowMaximize: 'window:maximize',
	windowClose: 'window:close',
	windowIsMaximized: 'window:isMaximized',
	windowMaximizedChange: 'window:maximizedChange',
	// Queue commands — renderer → main. The QueueService on main is the
	// queue-of-record; renderer mutations are forbidden.
	queueCmdAdd: 'queue:cmd:add',
	queueCmdGetSnapshot: 'queue:cmd:getSnapshot',
	queueCmdStart: 'queue:cmd:start',
	queueCmdPause: 'queue:cmd:pause',
	queueCmdResume: 'queue:cmd:resume',
	queueCmdCancel: 'queue:cmd:cancel',
	queueCmdRetry: 'queue:cmd:retry',
	queueCmdClearCompleted: 'queue:cmd:clearCompleted',
	queueCmdRemove: 'queue:cmd:remove',
	queueCmdSetLane: 'queue:cmd:setLane',
	queueCmdApplySelectionAction: 'queue:cmd:applySelectionAction',
	queueCmdChangeOutputTarget: 'queue:cmd:changeOutputTarget',
	queueCmdPauseAll: 'queue:cmd:pauseAll',
	queueCmdResumeAll: 'queue:cmd:resumeAll',
	// Queue events — main → renderer. `snapshot` fires once on window create
	// (initial hydration); the others stream incremental diffs.
	queueEventSnapshot: 'queue:event:snapshot',
	queueEventAdded: 'queue:event:added',
	queueEventUpdated: 'queue:event:updated',
	queueEventRemoved: 'queue:event:removed',
	updaterAvailable: 'updater:available',
	updaterInstall: 'updater:install',
	eventsClipboardUrl: 'events:clipboardUrl',
	analyticsTrack: 'analytics:track',
	diagnosticsLogWizardStep: 'diagnostics:logWizardStep',
	warmupProgress: 'warmup:progress',
	dialogChooseExecutable: 'dialog:chooseExecutable',
	shellOpenBinariesDir: 'shell:openBinariesDir',
	playlistScanFolder: 'playlist:scanFolder',
	playlistRegisterManifest: 'playlist:registerManifest',
	// Library — media
	libraryMediaList: 'library:media:list',
	libraryMediaGet: 'library:media:get',
	libraryMediaSearch: 'library:media:search',
	libraryMediaSetFavorite: 'library:media:setFavorite',
	libraryMediaSetStatus: 'library:media:setStatus',
	libraryMediaDelete: 'library:media:delete',
	libraryMediaCount: 'library:media:count',
	libraryMediaCountByStatus: 'library:media:countByStatus',
	// Library — collections
	libraryCollectionList: 'library:collection:list',
	libraryCollectionGet: 'library:collection:get',
	libraryCollectionCreate: 'library:collection:create',
	libraryCollectionUpdate: 'library:collection:update',
	libraryCollectionDelete: 'library:collection:delete',
	libraryCollectionAddMedia: 'library:collection:addMedia',
	libraryCollectionRemoveMedia: 'library:collection:removeMedia',
	libraryCollectionGetMediaIds: 'library:collection:getMediaIds',
	libraryCollectionGetForMedia: 'library:collection:getForMedia',
	// Library — tags
	libraryTagList: 'library:tag:list',
	libraryTagCreate: 'library:tag:create',
	libraryTagUpdate: 'library:tag:update',
	libraryTagDelete: 'library:tag:delete',
	libraryTagAddToMedia: 'library:tag:addToMedia',
	libraryTagRemoveFromMedia: 'library:tag:removeFromMedia',
	libraryTagGetForMedia: 'library:tag:getForMedia',
	libraryTagGetMediaIds: 'library:tag:getMediaIds',
	// Library — playback history
	libraryPlaybackUpdatePosition: 'library:playback:updatePosition',
	libraryPlaybackGetByMedia: 'library:playback:getByMedia',
	libraryPlaybackListRecent: 'library:playback:listRecent',
	// Library — download history
	libraryDownloadHistoryList: 'library:downloadHistory:list',
	libraryDownloadHistoryCount: 'library:downloadHistory:count',
	libraryDownloadHistoryCountByStatus: 'library:downloadHistory:countByStatus',
	// Library events — main → renderer
	libraryMediaCreated: 'library:media:created'
} as const
