export const IPC_CHANNELS = {
	appWarmUp: 'app:warmUp',
	appCancelWarmup: 'app:cancelWarmup',
	appInstallYtDlpHomebrew: 'app:installYtDlpHomebrew',
	appInstallYtDlpWinget: 'app:installYtDlpWinget',
	downloadsStart: 'downloads:start',
	downloadsCancel: 'downloads:cancel',
	downloadsPause: 'downloads:pause',
	downloadsResume: 'downloads:resume',
	downloadsProbe: 'downloads:probe',
	downloadsProbeCancel: 'downloads:probeCancel',
	chooseFolder: 'dialog:chooseFolder',
	chooseFile: 'dialog:chooseFile',
	settingsGet: 'settings:get',
	settingsUpdate: 'settings:update',
	appSetLanguage: 'app:setLanguage',
	shellOpenFolder: 'shell:openFolder',
	shellOpenExternal: 'shell:openExternal',
	logsOpenDir: 'logs:openDir',
	logsUploadFeedbackDiagnostic: 'logs:uploadFeedbackDiagnostic',
	eventsStatus: 'events:status',
	eventsProgress: 'events:progress',
	windowMinimize: 'window:minimize',
	windowMaximize: 'window:maximize',
	windowClose: 'window:close',
	windowIsMaximized: 'window:isMaximized',
	windowMaximizedChange: 'window:maximizedChange',
	// Queue commands — renderer → main. The QueueService on main is the
	// queue-of-record; renderer mutations are forbidden.
	queueCmdAdd: 'queue:cmd:add',
	queueCmdGetSnapshot: 'queue:cmd:getSnapshot',
	queueCmdStart: 'queue:cmd:start',
	queueCmdPause: 'queue:cmd:pause',
	queueCmdResume: 'queue:cmd:resume',
	queueCmdCancel: 'queue:cmd:cancel',
	queueCmdRetry: 'queue:cmd:retry',
	queueCmdClearCompleted: 'queue:cmd:clearCompleted',
	queueCmdRemove: 'queue:cmd:remove',
	queueCmdSetLane: 'queue:cmd:setLane',
	queueCmdPauseAll: 'queue:cmd:pauseAll',
	queueCmdResumeAll: 'queue:cmd:resumeAll',
	// Queue events — main → renderer. `snapshot` fires once on window create
	// (initial hydration); the others stream incremental diffs.
	queueEventSnapshot: 'queue:event:snapshot',
	queueEventAdded: 'queue:event:added',
	queueEventUpdated: 'queue:event:updated',
	queueEventRemoved: 'queue:event:removed',
	updaterAvailable: 'updater:available',
	updaterInstall: 'updater:install',
	eventsClipboardUrl: 'events:clipboardUrl',
	analyticsTrack: 'analytics:track',
	diagnosticsLogWizardStep: 'diagnostics:logWizardStep',
	warmupProgress: 'warmup:progress',
	dialogChooseExecutable: 'dialog:chooseExecutable',
	shellOpenBinariesDir: 'shell:openBinariesDir',
	playlistScanFolder: 'playlist:scanFolder',
	playlistRegisterManifest: 'playlist:registerManifest'
} as const
